version: '3'
services:
  database:
   image: postgres:latest
   restart: always
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=greenlight
   ports:
    - '5432:5432'
   volumes:
     - ./db_data:/var/lib/postgresql/data
volumes:
  db:
   driver: local